#!/usr/bin/env bash
# BPS-Motif WITHIN-PIECE (clip-isolated) WINDOW-SIZE breaking-point sweep.
#
# Runs the full 13-layer + meanall CLaMP3-symbolic-abc sweep for EACH window size
# N (in bars) — so every window length is scored at its OWN best layer (bigger N
# may prefer a deeper layer). The per-N configs are generated by
# scripts/sweeps/gen_within_piece_n_configs.py from the canonical N4 templates;
# each uses the generic BPSMotifWithinPieceABC{Test,Dummy} dataset class with a
# per-N jsonl_template init arg. wandb group `CLaMP3-symbolic-abc /
# BPSMotifWithinPieceN{N}`, job_type test, zero-shot (max_epochs=0, no ckpts).
#
# Build each window's dataset first (windows shrink as N grows):
#   for N in 1 2 4 6 8 12 16 24 32; do
#     uv run python scripts/data/build_bps_motif_within_piece.py --window "$N" --workers 8
#   done
# Generate the per-N configs (N4 is the source template, skipped):
#   uv run python scripts/sweeps/gen_within_piece_n_configs.py --windows 1 2 6 8 12 16 24 32
#
# Usage:
#   scripts/sweeps/run_bps_within_piece_n.sh --windows "1 2 4 6 8 12 16 24 32" \
#       [--accelerator gpu] [--concurrency 4] [--layers "0 1 ... 12"]
#
# Runs the N sweeps SEQUENTIALLY (each is itself --concurrency-parallel over its
# 13 layers). To run two N-sweeps concurrently (if VRAM allows), launch this
# script twice in separate tmux windows with disjoint --windows sets.
set -uo pipefail

ACCEL="gpu"
CONCURRENCY="4"
WINDOWS="1 2 4 6 8 12 16 24 32"
LAYERS_ARG=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --accelerator) ACCEL="$2"; shift 2 ;;
    --concurrency) CONCURRENCY="$2"; shift 2 ;;
    --windows) WINDOWS="$2"; shift 2 ;;
    --layers) LAYERS_ARG="$2"; shift 2 ;;
    *) echo "unknown arg: $1"; exit 2 ;;
  esac
done

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO" || exit 1
[[ "$ACCEL" == "mps" ]] && export PYTORCH_ENABLE_MPS_FALLBACK=1
PY="$REPO/.venv/bin/python"

EXTRA_LAYERS=()
[[ -n "$LAYERS_ARG" ]] && EXTRA_LAYERS=(--layers $LAYERS_ARG)

for N in $WINDOWS; do
  BASE="configs/probe.CLaMP3-symbolic-abc-layers.BPSMotifWithinPieceN${N}.yaml"
  if [[ ! -f "$BASE" ]]; then
    echo "!! missing config $BASE — run gen_within_piece_n_configs.py --windows $N first; skipping N=$N" >&2
    continue
  fi
  echo "===== WITHIN-PIECE-N${N}-ABC sweep (accel=${ACCEL}, conc=${CONCURRENCY}) ====="
  "$PY" scripts/sweeps/run_sweep_local.py \
    --base-config "$BASE" \
    --num-layers 13 --model-tag CLaMP3-symbolic-abc --task-tag "BPSMotifWithinPieceN${N}" \
    --accelerator "$ACCEL" --concurrency "$CONCURRENCY" --skip-fit-if-no-train \
    "${EXTRA_LAYERS[@]}"
  echo "===== WITHIN-PIECE-N${N}-ABC sweep complete ====="
done
