"""marble/utils/emb_cache.py
─────────────────────────────────
Per-clip post-time-pool embedding cache for frozen-encoder probe sweeps.

Why this exists
---------------
Every per-layer subprocess in a layer sweep re-runs the encoder forward
over the entire dataset. For OMAR-RQ × SHS100K that means 5,000 audio
clips × 24 layers = ~13 hours of redundant work; the encoder is frozen,
returns all layers in one forward, and ``TimeAvgPool`` mean-pools the
time axis away regardless of which layer is picked. So we cache the
``(L, H)`` per-clip post-time-pool tensor exactly once, then every
subsequent (per-layer or meanall) sweep job loads tensors instead of
running the encoder.

Critical commutativity lemma (verified): ``mean_L(mean_T(x)) ==
mean_T(mean_L(x))`` because both operations are linear. So the same
``(L, H)`` cache serves **both** per-layer queries (pick layer N from
the L axis) **and** meanall queries (mean over L). No separate cache
for meanall is needed.

Cache layout
------------
::

    output/.emb_cache/
      <encoder_slug>/                           # e.g. OMARRQ-multifeature-25hz
        <task_name>__<config_hash>/             # e.g. SHS100K__a3b8c1d2
          _meta.json                            # human-readable cache key
          <clip_id>.pt                          # (L, H) fp32 tensor
          <clip_id>.pt
          ...

``<config_hash>`` is the first 8 hex chars of
sha256(model_id + sample_rate + clip_seconds + audio_pipeline_signature)
so different encoder configs (different clip lengths, different
audio preprocessing) get isolated cache directories without collisions.

``<clip_id>`` is generated by callers with :func:`make_clip_id` so
filesystem-unsafe characters in audio paths can't break things and
two files with the same basename in different folders don't collide.

Concurrency
-----------
Writes are atomic via ``write to <name>.<pid>.tmp + os.replace``. Race
results from concurrent layer subprocesses are benign — the tensor data
is identical regardless of which writer wins (frozen encoder, same
input → same output).
"""

from __future__ import annotations

import hashlib
import json
import os
import threading
from pathlib import Path
from typing import Any

import torch

DEFAULT_CACHE_ROOT = Path("output") / ".emb_cache"


# ──────────────────────────────────────────────────────────────────────────
# Cache-key + clip-id derivation
# ──────────────────────────────────────────────────────────────────────────


def make_clip_id(audio_path: str, slice_idx: int = 0) -> str:
    """Build a filesystem-safe, collision-resistant identifier for one
    encoder input.

    Format: ``<stem>__<sha1(path)[:8]>__c<slice_idx>``.
    The path hash prevents collisions when two files share a stem
    (e.g. ``track01.mp3`` in different artist folders).
    """
    stem = Path(audio_path).stem
    # Hash the full normalised path so equivalent paths on different OSes
    # collide consistently. Use forward slashes for cross-platform stability.
    norm = str(Path(audio_path).as_posix())
    h = hashlib.sha1(norm.encode("utf-8")).hexdigest()[:8]
    return f"{stem}__{h}__c{int(slice_idx)}"


def compute_config_hash(
    *,
    encoder_model_id: str,
    sample_rate: int | float,
    clip_seconds: float,
    pipeline_signature: str = "",
) -> str:
    """Stable short hash that invalidates the cache when the encoder
    input pipeline changes meaningfully.

    Includes: HuggingFace/checkpoint id, target sample rate, clip
    length in seconds, and an opaque pipeline signature (caller-built
    from the audio_transforms class names) so a swap from e.g.
    ``MERT_FeatureExtractor`` to ``OMARRQ_FeatureExtractor`` lands in
    a new cache dir rather than feeding the head wrong embeddings.
    """
    h = hashlib.sha256()
    h.update(str(encoder_model_id).encode("utf-8"))
    h.update(b"|")
    h.update(str(int(sample_rate)).encode("utf-8"))
    h.update(b"|")
    h.update(f"{float(clip_seconds):.6f}".encode())
    h.update(b"|")
    h.update(str(pipeline_signature).encode("utf-8"))
    return h.hexdigest()[:8]


# ──────────────────────────────────────────────────────────────────────────
# Cache class
# ──────────────────────────────────────────────────────────────────────────


class EmbeddingCache:
    """File-backed key→tensor store for per-clip ``(L, H)`` embeddings.

    Parameters
    ----------
    encoder_slug : str
        Human-readable encoder identifier used as the top-level directory
        (e.g. ``"OMARRQ-multifeature-25hz"`` or ``"MERT-v1-95M"``).
    task_name : str
        Task identifier used in the directory name (e.g. ``"SHS100K"``).
    config_hash : str
        Short hash produced by :func:`compute_config_hash` — bumps when
        the encoder input pipeline changes.
    metadata : dict | None
        Human-readable key contents to dump into ``_meta.json``. None of
        these fields affect the cache key itself — they're just for
        ``manage.py --info`` and debugging.
    root : Path | None
        Cache root. Defaults to ``output/.emb_cache``.
    log_first_n : int
        Print a single info line on the first N cache decisions
        (hit/miss) per cache instance, so the user can see at a glance
        whether the cache kicked in. Default 1.
    """

    def __init__(
        self,
        *,
        encoder_slug: str,
        task_name: str,
        config_hash: str,
        metadata: dict[str, Any] | None = None,
        root: Path | None = None,
        log_first_n: int = 1,
    ):
        if root is None:
            root = DEFAULT_CACHE_ROOT
        self.dir = Path(root) / encoder_slug / f"{task_name}__{config_hash}"
        self.dir.mkdir(parents=True, exist_ok=True)

        # Write/refresh _meta.json. Atomic to survive concurrent writers.
        meta_path = self.dir / "_meta.json"
        meta_body = {
            "encoder_slug": encoder_slug,
            "task_name": task_name,
            "config_hash": config_hash,
            **(metadata or {}),
        }
        self._atomic_write_text(meta_path, json.dumps(meta_body, indent=2))

        self._log_first_n = int(log_first_n)
        self._log_used = 0
        self._lock = threading.Lock()

    # ── pickling support ─────────────────────────────────────────────────
    # `EmbeddingCache` instances get pickled when DataLoader workers spawn
    # on Windows (spawn-mode multiprocessing) — `BaseTask` injects
    # `cache_check_fn = self._cache.has` into datasets, so each dataset
    # holds a bound method that pickles the parent cache. `threading.Lock`
    # is not picklable, so __getstate__ drops it and __setstate__
    # recreates a fresh lock in the worker. Workers only call `.has()`
    # (file existence check, no locking needed); the lock guards
    # `maybe_log` which only ever fires in the main process.

    def __getstate__(self):
        state = self.__dict__.copy()
        state.pop("_lock", None)
        return state

    def __setstate__(self, state):
        self.__dict__.update(state)
        self._lock = threading.Lock()

    # ── public API ──────────────────────────────────────────────────────

    def path_for(self, clip_id: str) -> Path:
        """File path for one clip's cached tensor."""
        # Defensive: clip_id should already be filesystem-safe, but strip
        # any path separators just in case a caller passes a raw audio path.
        safe = clip_id.replace("/", "_").replace("\\", "_")
        return self.dir / f"{safe}.pt"

    def has(self, clip_id: str) -> bool:
        return self.path_for(clip_id).exists()

    def get(self, clip_id: str) -> torch.Tensor:
        """Load one ``(L, H)`` tensor. Raises ``FileNotFoundError`` on miss."""
        p = self.path_for(clip_id)
        data = torch.load(p, map_location="cpu", weights_only=True)
        return data["embedding"] if isinstance(data, dict) else data

    def put(self, clip_id: str, embedding: torch.Tensor) -> None:
        """Atomically write one ``(L, H)`` tensor to disk.

        Stored as fp32 regardless of the input dtype — the 2× disk vs fp16
        is negligible at our scale (~96 KB/clip for OMAR-RQ) and avoids
        any precision regression vs the un-cached baseline.
        """
        if embedding.ndim != 2:
            raise ValueError(
                f"EmbeddingCache.put expected (L, H) tensor; got shape {tuple(embedding.shape)}"
            )
        emb = embedding.detach().to(torch.float32).cpu().contiguous()
        target = self.path_for(clip_id)
        tmp = target.with_name(f"{target.name}.{os.getpid()}.tmp")
        # torch.save handles its own atomicity at the filesystem level via
        # a small write; we add the explicit .tmp + os.replace dance so
        # truly concurrent writers (--concurrency>1 on the same clip)
        # don't see a half-written file.
        torch.save({"embedding": emb}, tmp)
        os.replace(tmp, target)

    def has_all(self, clip_ids: list[str]) -> bool:
        return all(self.has(c) for c in clip_ids)

    def get_batch(self, clip_ids: list[str]) -> torch.Tensor:
        """Stack ``(L, H)`` per clip → ``(B, L, H)``."""
        tensors = [self.get(c) for c in clip_ids]
        return torch.stack(tensors, dim=0)

    def put_batch(self, clip_ids: list[str], embeddings: torch.Tensor) -> None:
        """Save ``(B, L, H)`` as one file per clip."""
        if embeddings.ndim != 3:
            raise ValueError(
                f"EmbeddingCache.put_batch expected (B, L, H) tensor; got "
                f"shape {tuple(embeddings.shape)}"
            )
        if len(clip_ids) != embeddings.size(0):
            raise ValueError(f"clip_ids length {len(clip_ids)} != batch dim {embeddings.size(0)}")
        for cid, emb in zip(clip_ids, embeddings, strict=True):
            self.put(cid, emb)

    # ── instrumentation ─────────────────────────────────────────────────

    def maybe_log(self, *, hit: bool, n_clips: int) -> None:
        """Print a one-time confirmation line so the user can see whether
        the cache engaged. Suppressed after ``log_first_n`` events."""
        with self._lock:
            if self._log_used >= self._log_first_n:
                return
            self._log_used += 1
        msg_kind = "HIT " if hit else "MISS"
        # Display the cache dir relative to the default `output/` root
        # when we can; otherwise fall back to the absolute path. The
        # smoke test (and `extract.py --root=...`) can set a custom
        # root that isn't under `output/`, so we can't assume that
        # relative path exists.
        try:
            dir_display = str(self.dir.relative_to(Path("output")))
        except ValueError:
            dir_display = str(self.dir)
        print(f"[emb_cache] {msg_kind} on first lookup ({n_clips} clips, dir={dir_display})")

    # ── internals ────────────────────────────────────────────────────────

    @staticmethod
    def _atomic_write_text(target: Path, text: str) -> None:
        tmp = target.with_name(f"{target.name}.{os.getpid()}.tmp")
        tmp.write_text(text)
        os.replace(tmp, target)


# ──────────────────────────────────────────────────────────────────────────
# Helpers for callers integrating the cache into a probe task
# ──────────────────────────────────────────────────────────────────────────


def pipeline_signature_from_transforms(transforms: list[Any]) -> str:
    """Stable string from a list of audio transform instances (or class
    names). Used as one input to ``compute_config_hash``."""
    parts: list[str] = []
    for t in transforms:
        if isinstance(t, str):
            parts.append(t)
        elif hasattr(t, "__class__"):
            parts.append(t.__class__.__name__)
        else:
            parts.append(repr(t))
    return "|".join(parts)


def stacked_to_layer_tuple(stacked: torch.Tensor) -> tuple[torch.Tensor, ...]:
    """Convert a cached ``(B, L, H)`` tensor back to the tuple-of-tensors
    format that ``LayerSelector`` expects from the encoder.

    Each emitted tensor has shape ``(B, 1, H)`` — a single time-step,
    since the cached values are already time-pooled. Downstream
    ``LayerSelector`` indexes into the tuple and stacks back to
    ``(B, L_selected, 1, H)``; ``TimeAvgPool`` then no-ops on the
    already-size-1 time axis. End result identical to the un-cached
    path (modulo fp rounding).
    """
    if stacked.ndim != 3:
        raise ValueError(f"stacked_to_layer_tuple expected (B, L, H); got {tuple(stacked.shape)}")
    return tuple(stacked[:, i, :].unsqueeze(1) for i in range(stacked.shape[1]))


def encoder_tuple_to_pooled(layer_outputs: tuple[torch.Tensor, ...]) -> torch.Tensor:
    """Time-pool a tuple of ``(B, T, H_l)`` tensors → ``(B, L, H)``.

    Used by the cache miss path: encoder output is a tuple per layer;
    we mean over the time axis per layer then stack across layers to
    match what ``stacked_to_layer_tuple`` would unpack on a hit.
    """
    pooled = [h.mean(dim=1) for h in layer_outputs]  # each (B, H_l)
    return torch.stack(pooled, dim=1)  # (B, L, H)


# ──────────────────────────────────────────────────────────────────────────
# Mixin — shared cache plumbing for any LightningModule with the standard
# encoder + emb_transforms + (decoder) pipeline
# ──────────────────────────────────────────────────────────────────────────


class EmbeddingCacheMixin:
    """Reusable cache-plumbing logic for any task with the standard MARBLE
    pipeline ``encoder(x) → emb_transforms → (decoder)``.

    Both :class:`marble.core.base_task.BaseTask` and the retrieval-only
    :class:`marble.tasks.Covers80.probe.CoverRetrievalTask` inherit from
    this mixin. The mixin doesn't override ``forward()`` itself — instead
    it exposes :meth:`_cached_forward_to_emb_transform_input` which the
    concrete ``forward()`` calls to obtain the layer-tuple representation
    (either freshly encoded or loaded from disk).

    The hosting class is expected to have:
      * ``self.encoder`` returning a tuple of ``(B, T, H_l)`` per layer
      * ``self.emb_transforms`` (a list — not consumed by the mixin)
      * ``self.sample_rate`` (int, used as a fallback for cache key)
      * ``self.cache_embeddings`` (bool, set in the host's ``__init__``)
      * ``self.trainer`` set when in Lightning's lifecycle (optional)

    Cache instance is built lazily on first forward via
    :meth:`_ensure_cache` — we need access to the trainer's datamodule
    to derive clip_seconds and the audio pipeline signature.
    """

    # Slots (set by host __init__ via `self.cache_embeddings = ...; mixin.__init__(self)`)
    _cache: EmbeddingCache | None
    _cache_init_attempted: bool
    cache_embeddings: bool
    sample_rate: int | float
    encoder: Any

    def _init_cache_state(self) -> None:
        """Initialize the mixin's slots. Hosts should call this from
        their ``__init__`` AFTER ``self.cache_embeddings = bool(...)``."""
        self._cache = None
        self._cache_init_attempted = False

    # ── lazy cache construction ──────────────────────────────────────────

    def _ensure_cache(self) -> None:
        """Build the EmbeddingCache once the trainer + datamodule are
        wired up. Safe to call repeatedly; only the first call does work."""
        if self._cache is not None or self._cache_init_attempted:
            return
        self._cache_init_attempted = True
        if not getattr(self, "cache_embeddings", False):
            return
        encoder_slug, task_name = self._derive_cache_slugs()
        model_id = getattr(self.encoder, "HUGGINGFACE_MODEL_NAME", encoder_slug)
        sr = int(getattr(self.encoder, "sampling_rate", self.sample_rate))
        clip_seconds = self._derive_clip_seconds()
        pipeline_sig = self._derive_pipeline_signature()
        config_hash = compute_config_hash(
            encoder_model_id=model_id,
            sample_rate=sr,
            clip_seconds=clip_seconds,
            pipeline_signature=pipeline_sig,
        )
        self._cache = EmbeddingCache(
            encoder_slug=encoder_slug,
            task_name=task_name,
            config_hash=config_hash,
            metadata={
                "encoder_model_id": str(model_id),
                "sample_rate": sr,
                "clip_seconds": float(clip_seconds),
                "pipeline_signature": pipeline_sig,
            },
        )

    def _derive_cache_slugs(self) -> tuple[str, str]:
        """Return ``(encoder_slug, task_name)`` derived from the WandB
        group name when available; fall back to class names."""
        group = None
        try:
            logger = self.trainer.logger  # type: ignore[attr-defined]
            init_args = getattr(logger, "_wandb_init", None) or {}
            group = init_args.get("group")
        except Exception:
            group = None
        if isinstance(group, str) and " / " in group:
            enc, task = group.split(" / ", 1)
            return enc.strip(), task.strip()
        enc = type(self.encoder).__name__
        task = type(self).__name__
        return enc, task

    def _derive_clip_seconds(self) -> float:
        try:
            test_cfg = self.trainer.datamodule.test_config  # type: ignore[attr-defined]
            init_args = test_cfg.get("init_args", {})
            cs = init_args.get("clip_seconds")
            if cs is not None:
                return float(cs)
        except Exception:
            pass
        return 0.0

    def _derive_pipeline_signature(self) -> str:
        try:
            transforms = self.trainer.datamodule.audio_transforms.get("test", [])  # type: ignore[attr-defined]
            sig_parts = [t.get("class_path", repr(t)) for t in transforms]
            return "|".join(sig_parts)
        except Exception:
            return ""

    # ── cache-aware forward helpers ──────────────────────────────────────

    def _cached_forward_layer_tuple(
        self,
        x: torch.Tensor,
        clip_ids: list[str] | None,
    ) -> tuple[torch.Tensor, ...]:
        """Return the layer-tuple representation ``(L tensors of (B, T, H_l))``
        for the input batch, either by reading from cache or by running the
        encoder forward and persisting the pooled result.

        Callers should then run ``self.emb_transforms`` on the returned
        tuple, exactly as they would on a raw encoder output.

        On cache hits the time axis collapses to T=1 — ``LayerSelector``
        treats the tuple unchanged, and ``TimeAvgPool`` is a no-op on
        T=1 inputs.
        """
        self._ensure_cache()
        use_cache = self._cache is not None and clip_ids is not None

        if use_cache and self._cache.has_all(clip_ids):
            cached = self._cache.get_batch(clip_ids).to(x.device)  # (B, L, H)
            self._cache.maybe_log(hit=True, n_clips=len(clip_ids))
            return stacked_to_layer_tuple(cached)

        # Miss path — run encoder, optionally persist.
        layer_outputs = self.encoder(x)
        # Normalize HuggingFace BaseModelOutput → its `.hidden_states`
        # tuple. The standard non-cache flow (BaseEmbTransform.__call__)
        # does this transparently before LayerSelector; the cache miss
        # path bypasses that wrapper, so we replicate it here.
        # OMAR-RQ / MuQ encoders already return a plain tuple (no
        # `.hidden_states` attribute) → no-op for them.
        if hasattr(layer_outputs, "hidden_states"):
            layer_outputs = layer_outputs.hidden_states
        if use_cache:
            pooled = encoder_tuple_to_pooled(layer_outputs)  # (B, L, H)
            self._cache.put_batch(clip_ids, pooled)
            self._cache.maybe_log(hit=False, n_clips=len(clip_ids))
            return stacked_to_layer_tuple(pooled)
        return layer_outputs

    # ── audio-I/O bypass injection ───────────────────────────────────────

    def _inject_cache_check_into_datasets(self) -> None:
        """Walk the wired-up datamodule and set ``cache_check_fn`` on every
        dataset that supports it, so audio decode can be skipped on cache
        hits. Safe to call multiple times — the fn is idempotent.

        Should be invoked from the host's ``setup()`` once the trainer +
        datamodule are attached.
        """
        if self._cache is None:
            return
        try:
            dm = self.trainer.datamodule  # type: ignore[attr-defined]
        except Exception:
            return
        if dm is None:
            return
        for attr in ("train_dataset", "val_dataset", "test_dataset"):
            ds = getattr(dm, attr, None)
            # AudioTransformDataset wraps the real dataset under .base
            while ds is not None and hasattr(ds, "base"):
                ds = ds.base
            if ds is not None and hasattr(ds, "cache_check_fn"):
                ds.cache_check_fn = self._cache.has
